# Welcome to Jekyll!
#

# Site settings
title: Ariela Lu Ye
description: |
  Ph.D. in Linguistics <br />
  RUTGERS UNIVERSITY
owner: Ariela Lu Ye # or company name
first_published: # if migrating another site, the year of your first publish
email: arielaluye@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arielaluye.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/arielaluye
  #linkedin-square: https://linkedin.com/in/yifanyang08
  facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: /5Contact.html
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
